package com.techpulse.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Brand colors
val TechPulsePrimary = Color(0xFF6366F1)       // Indigo
val TechPulseSecondary = Color(0xFF8B5CF6)     // Violet
val TechPulseTertiary = Color(0xFF06B6D4)      // Cyan

// Section-specific colors — Hot/Trending (Red)
val TrendingPrimary = Color(0xFFEF4444)
val TrendingContainer = Color(0xFFFEE2E2)
val TrendingOnContainer = Color(0xFF991B1B)
val TrendingDarkContainer = Color(0xFF7F1D1D)
val TrendingOnDarkContainer = Color(0xFFFCA5A5)

// Section-specific colors — New Releases (Blue)
val ReleasesPrimary = Color(0xFF3B82F6)
val ReleasesContainer = Color(0xFFDBEAFE)
val ReleasesOnContainer = Color(0xFF1E3A8A)
val ReleasesDarkContainer = Color(0xFF1E3A8A)
val ReleasesOnDarkContainer = Color(0xFF93C5FD)

// Section-specific colors — Quick Tips (Green)
val TipsPrimary = Color(0xFF22C55E)
val TipsContainer = Color(0xFFDCFCE7)
val TipsOnContainer = Color(0xFF166534)
val TipsDarkContainer = Color(0xFF14532D)
val TipsOnDarkContainer = Color(0xFF86EFAC)

// Section-specific colors — Learning Path (Amber)
val LearningPrimary = Color(0xFFF59E0B)
val LearningContainer = Color(0xFFFEF3C7)
val LearningOnContainer = Color(0xFF92400E)
val LearningDarkContainer = Color(0xFF78350F)
val LearningOnDarkContainer = Color(0xFFFCD34D)

// Section-specific colors — Deep Dive (Purple)
val DeepDivePrimary = Color(0xFFA855F7)
val DeepDiveContainer = Color(0xFFF3E8FF)
val DeepDiveOnContainer = Color(0xFF6B21A8)
val DeepDiveDarkContainer = Color(0xFF581C87)
val DeepDiveOnDarkContainer = Color(0xFFD8B4FE)

// Light color scheme tokens
val LightPrimary = Color(0xFF6366F1)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE0E0FF)
val LightOnPrimaryContainer = Color(0xFF1A1B4B)
val LightSecondary = Color(0xFF8B5CF6)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFEDE9FE)
val LightOnSecondaryContainer = Color(0xFF2E1065)
val LightTertiary = Color(0xFF06B6D4)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFCFFAFE)
val LightOnTertiaryContainer = Color(0xFF164E63)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightOnSurfaceVariant = Color(0xFF475569)
val LightError = Color(0xFFDC2626)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFEE2E2)
val LightOnErrorContainer = Color(0xFF991B1B)
val LightOutline = Color(0xFFCBD5E1)
val LightOutlineVariant = Color(0xFFE2E8F0)

// Dark color scheme tokens
val DarkPrimary = Color(0xFFA5B4FC)
val DarkOnPrimary = Color(0xFF1E1B4B)
val DarkPrimaryContainer = Color(0xFF3730A3)
val DarkOnPrimaryContainer = Color(0xFFE0E0FF)
val DarkSecondary = Color(0xFFC4B5FD)
val DarkOnSecondary = Color(0xFF2E1065)
val DarkSecondaryContainer = Color(0xFF5B21B6)
val DarkOnSecondaryContainer = Color(0xFFEDE9FE)
val DarkTertiary = Color(0xFF67E8F9)
val DarkOnTertiary = Color(0xFF164E63)
val DarkTertiaryContainer = Color(0xFF0E7490)
val DarkOnTertiaryContainer = Color(0xFFCFFAFE)
val DarkBackground = Color(0xFF0F172A)
val DarkOnBackground = Color(0xFFE2E8F0)
val DarkSurface = Color(0xFF1E293B)
val DarkOnSurface = Color(0xFFE2E8F0)
val DarkSurfaceVariant = Color(0xFF334155)
val DarkOnSurfaceVariant = Color(0xFF94A3B8)
val DarkError = Color(0xFFFCA5A5)
val DarkOnError = Color(0xFF7F1D1D)
val DarkErrorContainer = Color(0xFF991B1B)
val DarkOnErrorContainer = Color(0xFFFEE2E2)
val DarkOutline = Color(0xFF475569)
val DarkOutlineVariant = Color(0xFF334155)
